# Generated by Django 5.2.10 on 2026-01-13 22:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("invoice_paid", "Invoice Paid"),
                            ("transaction_confirmed", "Transaction Confirmed"),
                            ("gas_sponsored", "Gas Sponsored"),
                        ],
                        max_length=50,
                    ),
                ),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_email", models.EmailField(blank=True, max_length=254)),
                (
                    "client_wallet",
                    models.CharField(
                        blank=True,
                        max_length=42,
                        validators=[django.core.validators.MinLengthValidator(42)],
                    ),
                ),
                ("client_name", models.CharField(blank=True, max_length=255)),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USDC", "USDC"), ("USD", "USD")],
                        default="USDC",
                        max_length=4,
                    ),
                ),
                ("contract_invoice_id", models.BigIntegerField(blank=True, null=True)),
                ("contract_address", models.CharField(blank=True, max_length=42)),
                ("tx_hash", models.CharField(blank=True, max_length=66)),
                ("payment_tx_hash", models.CharField(blank=True, max_length=66)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("pending", "Pending Payment"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_on_chain", models.BooleanField(default=False)),
                ("gas_sponsored", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ipfs_hash", models.CharField(blank=True, max_length=100)),
                (
                    "payment_link_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=32, unique=True
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=6, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "short_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_link",
                        to="invoices.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tx_hash",
                    models.CharField(db_index=True, max_length=66, unique=True),
                ),
                (
                    "tx_type",
                    models.CharField(
                        choices=[
                            ("invoice_created", "Invoice Created"),
                            ("invoice_paid", "Invoice Paid"),
                            ("withdrawal", "Withdrawal"),
                            ("deposit", "Deposit"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=6, max_digits=20)),
                ("token_address", models.CharField(blank=True, max_length=42)),
                ("token_symbol", models.CharField(default="USDC", max_length=10)),
                ("from_address", models.CharField(max_length=42)),
                ("to_address", models.CharField(max_length=42)),
                ("block_number", models.BigIntegerField(blank=True, null=True)),
                (
                    "gas_used",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=20, null=True
                    ),
                ),
                (
                    "gas_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=20, null=True
                    ),
                ),
                ("gas_sponsored", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["creator", "status"], name="invoices_in_creator_fdcf4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date"], name="invoices_in_due_dat_6cc0ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["payment_link_id"], name="invoices_in_payment_ab1593_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client_wallet"], name="invoices_in_client__354690_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentlink",
            index=models.Index(
                fields=["short_id"], name="invoices_pa_short_i_f6132f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["tx_hash"], name="invoices_tr_tx_hash_f92443_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "tx_type"], name="invoices_tr_user_id_5fad8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "created_at"], name="invoices_tr_status_371145_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["block_number"], name="invoices_tr_block_n_5a04ee_idx"
            ),
        ),
    ]
