# Generated by Django 5.2.10 on 2026-01-13 22:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("profile_picture", models.URLField(blank=True, max_length=500)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("preferred_currency", models.CharField(default="USD", max_length=3)),
                (
                    "wallet_address",
                    models.CharField(
                        blank=True,
                        max_length=42,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(42)],
                    ),
                ),
                ("wallet_type", models.CharField(blank=True, max_length=50)),
                ("is_wallet_connected", models.BooleanField(default=False)),
                ("last_wallet_connection", models.DateTimeField(blank=True, null=True)),
                (
                    "google_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "twitter_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "smart_account_address",
                    models.CharField(
                        blank=True,
                        max_length=42,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(42)],
                    ),
                ),
                ("smart_account_deployed", models.BooleanField(default=False)),
                (
                    "smart_account_deployment_tx",
                    models.CharField(blank=True, max_length=66),
                ),
                (
                    "total_earned_usdc",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                ("total_invoices", models.PositiveIntegerField(default=0)),
                ("total_paid_invoices", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("token", models.CharField(max_length=64, unique=True)),
                ("verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialLogin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("google", "Google"),
                            ("twitter", "Twitter"),
                            ("github", "GitHub"),
                        ],
                        max_length=20,
                    ),
                ),
                ("provider_user_id", models.CharField(max_length=255)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("profile_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_logins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("wallet_address", models.CharField(max_length=42)),
                ("chain_id", models.IntegerField()),
                ("wallet_type", models.CharField(max_length=50)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_user_email_6f2530_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["wallet_address"], name="users_user_wallet__c9e508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["smart_account_address"], name="users_user_smart_a_baacbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["google_id"], name="users_user_google__98b509_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["twitter_id"], name="users_user_twitter_905300_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(fields=["token"], name="users_email_token_c80ef6_idx"),
        ),
        migrations.AddIndex(
            model_name="emailverification",
            index=models.Index(
                fields=["user", "verified"], name="users_email_user_id_91dc99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sociallogin",
            index=models.Index(
                fields=["user", "provider"], name="users_socia_user_id_bef292_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sociallogin",
            unique_together={("provider", "provider_user_id")},
        ),
        migrations.AddIndex(
            model_name="walletsession",
            index=models.Index(
                fields=["user", "is_active"], name="users_walle_user_id_2c04c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="walletsession",
            index=models.Index(
                fields=["expires_at"], name="users_walle_expires_a5f5ad_idx"
            ),
        ),
    ]
